service: aws-python-http-api-project-personal
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  my_info:
    handler: handler.my_info
    events:
      - http:
          path: /my_info
          method: get
